# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_myorder_order_content_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_content',
            name='user',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
