# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-19 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_by', models.CharField(max_length=30)),
                ('sub_on', models.DateTimeField(auto_now_add=True)),
                ('topic', models.CharField(max_length=50)),
                ('matter', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('contact', models.BigIntegerField()),
                ('email', models.EmailField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('query', models.CharField(max_length=50)),
                ('ref', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('desc', models.TextField()),
                ('venue', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=256)),
                ('ans', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=256)),
                ('prod_name', models.CharField(max_length=30)),
                ('prod_id', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('offer', models.SmallIntegerField()),
                ('detail_desc', models.TextField()),
                ('avail', models.SmallIntegerField()),
            ],
        ),
    ]
