# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_auto_20170310_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='detail_desc',
        ),
        migrations.RemoveField(
            model_name='products',
            name='nut_1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='nut_2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='nut_3',
        ),
        migrations.RemoveField(
            model_name='products',
            name='nut_4',
        ),
        migrations.RemoveField(
            model_name='products',
            name='nut_5',
        ),
        migrations.AddField(
            model_name='products',
            name='Calcium',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='products',
            name='Calorific_value',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='products',
            name='Crude_Fibre',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='products',
            name='Energy',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='products',
            name='Fat',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='products',
            name='Fibre',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='products',
            name='Iron',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='products',
            name='Protein',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='products',
            name='Sodium',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='products',
            name='Sugar',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='products',
            name='Total_Carbohydrates',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AddField(
            model_name='products',
            name='Vitamin_C',
            field=models.CharField(default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='products',
            name='prod_name',
            field=models.CharField(max_length=25),
        ),
    ]
