# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20170301_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='address',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='query',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='ref',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='city',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='state',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
