# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-26 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_login_data_id'),
    ]

    operations = []
