# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-14 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_login_data_id'),
    ]

    operations = []
