# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-27 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20170226_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_data',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='login_data',
            name='contact',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='login_data',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='login_data',
            name='status',
            field=models.SmallIntegerField(default='0', null=True),
        ),
    ]
