# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170227_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='login_data',
            name='user',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
