# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170301_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_data',
            name='email',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='login_data',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
