# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170301_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_data',
            name='otp',
            field=models.SmallIntegerField(default='0', null=True),
        ),
    ]
