# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20170306_1948'),
    ]

    operations = [
    ]
