# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-01 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('contact', models.BigIntegerField(default=0)),
                ('email', models.CharField(max_length=100, null=True)),
                ('prod_name', models.CharField(max_length=15)),
                ('prod_id', models.IntegerField()),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('qty', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
